Add git branch check.
- Default check branch is master.
  - Avoids mistake of releasing off PR or other branches by mistake.
- Override with -b/--branch if releasing off another branch.
  - Allow releasing off of non-master branches when needed. (For
    example, bug fix release for older versions.)

diff --git a/pubnpm b/pubnpm
--- a/pubnpm
+++ b/pubnpm
@@ -27,6 +27,8 @@ Options:
   -v, --verbose  Verbose execution.
   -n, --dry-run  Dry run.
   -t, --tag=TAG  Use npm publish tag.
+  -b, --branch=BRANCH
+                 Ensure git branch (default: master, empty string to skip).
 " 1>&2
   exit
 }
@@ -41,6 +43,7 @@ Options:
   -v  Verbose execution.
   -n  Dry run.
   -t  Use npm publish tag.
+  -b  Ensure git branch (default: master, empty string to skip).
 " 1>&2
   exit
 }
@@ -62,11 +65,11 @@ else
 fi
 
 if [ "$GNU_GETOPT" = true ]; then
-  OPTS=`getopt -o hvnt: --long help,verbose,dry-run,tag: -n 'pubnpm' -- "$@"`
+  OPTS=`getopt -o hvnt:b: --long help,verbose,dry-run,tag,branch: -n 'pubnpm' -- "$@"`
   if [ $? != 0 ] ; then echo "ERROR: Failed parsing options." >&2 ; exit 1 ; fi
   eval set -- "$OPTS"
 else
-  OPTS=`getopt hvnt: $*`
+  OPTS=`getopt hvnt:b: $*`
   if [ $? != 0 ] ; then echo "ERROR: Failed parsing options." >&2 ; exit 1 ; fi
   eval set -- "$OPTS"
 fi
@@ -74,6 +77,7 @@ fi
 VERBOSE=false
 DRY_RUN=false
 TAG=
+BRANCH=master
 
 while true; do
   case "$1" in
@@ -81,6 +85,7 @@ while true; do
     -v|--verbose) VERBOSE=true; shift ;;
     -n|--dry-run) DRY_RUN=true; shift ;;
     -t|--tag) TAG="$2"; shift; shift ;;
+    -b|--branch) BRANCH="$2"; shift; shift ;;
     --) shift; break ;;
     *) break ;;
   esac
@@ -109,6 +114,7 @@ fi
 if [ "$VERBOSE" = true ]; then
   echo DRY_RUN=$DRY_RUN
   echo TAG=$TAG
+  echo BRANCH=$BRANCH
   echo VERSION_TYPE=$VERSION_TYPE
   echo PACKAGE_NAME=$PACKAGE_NAME
   echo PACKAGE_REPO=$PACKAGE_REPO
@@ -120,20 +126,46 @@ fi
 # check npm ownership access
 # always run, even in dry-run mode
 if [ "$VERBOSE" = true ]; then
-  echo "# NOTE: NPM checking package ownership"
+  echo "# NOTE: checking NPM package ownership"
 fi
 NPM_OWNS=$(npm owner ls | cut -d ' ' -f 1 | grep ^$NPM_WHOAMI$)
 
 if [ x"$NPM_WHOAMI" = x"$NPM_OWNS" ]; then
   if [ "$VERBOSE" = true ]; then
-    echo "# NOTE: NPM ownership check passed"
+    echo "# NOTE: NPM package ownership check passed"
   fi
 else
-  echo "ERROR: NPM ownership check failed"
+  echo "ERROR: NPM pacakge ownership check failed"
   if [ "$DRY_RUN" = true ]; then
-    echo "# NOTE: Continuing in dry-run mode with failed ownership check"
+    echo "# NOTE: Continuing in dry-run mode with failed NPM ownership check"
   else
     exit 1
+  fi
+fi
+
+# check git branch
+# always run, even in dry-run mode
+if [ "$VERBOSE" = true ]; then
+  echo "# NOTE: checking git branch"
+fi
+
+if [ x"$BRANCH" = x ]; then
+  if [ "$VERBOSE" = true ]; then
+    echo "# NOTE: git branch check skipped via options"
+  fi
+else
+  GIT_BRANCH=$(git branch --show-current)
+  if [ x"$BRANCH" = x"$GIT_BRANCH" ]; then
+    if [ "$VERBOSE" = true ]; then
+      echo "# NOTE: git branch check passed"
+    fi
+  else
+    echo "ERROR: git branch check failed (not on \"$BRANCH\")"
+    if [ "$DRY_RUN" = true ]; then
+      echo "# NOTE: Continuing in dry-run mode with failed git branch check"
+    else
+      exit 1
+    fi
   fi
 fi
 
@@ -175,7 +207,7 @@ if [ $(node -p "'build' in (require('./package.json').scripts || {})") = true ];
   echo '"build" script found, running install...'
   run_cmd npm install
 fi
-if [ x$TAG = x ]; then
+if [ x"$TAG" = x ]; then
   run_cmd npm publish
 else
   run_cmd npm publish --tag $TAG
